### ISSUE TITLE
Das Konvertieren großer Filme macht das System zeitweise unbenutzbar

### ISSUE THREAD

**Issue by uho** [McRip/wedeltube#2]
Wenn ein umfangreicher Filem konvertiert wird, verwendet FFMPEG 90+% der CPU-Zeit und verhindert
dadurch das Ausliefern von Filmen. Beim Versuch einen Filem dann abzuspielen verharrt das System minutenlang
im Media-Player bei "Laden...".

> top - 12:43:09 up 7 days,  2:07,  1 user,  load average: 1.15, 1.18, 0.69
> Tasks:  80 total,   2 running,  78 sleeping,   0 stopped,   0 zombie
> Cpu(s): 99.3%us,  0.7%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
> Mem:   1026096k total,   982060k used,    44036k free,     9544k buffers
> Swap:   916472k total,   529920k used,   386552k free,   287424k cached
> 
>  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND  
> 21027 administ  20   0 31520  10m 2620 R 98.3  1.0   5:36.35 ffmpeg  
> 10426 administ  20   0  539m 508m 1536 S  0.3 50.8   3:16.45 ruby  
> 19332 administ  20   0  537m  54m 1828 S  0.3  5.4   1:02.04 ruby  
> 20986 administ  20   0 60444  42m 2684 S  0.3  4.3   0:31.01 ruby  
> 21217 administ  20   0  2516 1152  904 R  0.3  0.1   0:00.05 top  
>     1 root      20   0  2764  492  264 S  0.0  0.0   0:03.25 init  
>     2 root      20   0     0    0    0 S  0.0  0.0   0:00.02 kthreadd

**Comment by uho** [comment]
Das Hängen beim Abspielen scheint sporadisch augzutreten und nicht unmittelbar mit der CPU-Belastung zusammenzuhängen. Browser: Safari 5.1/Mac

**Comment by LeBar** [comment]
Extern laufen die Videos anscheinend selbst in 720p problemlos und flüssig. Scheint also nur intern aufzutreten.

**Comment by maltehuebner** [comment]
Das Problem tritt nur innerhalb des Netzwerkes der Fachhochschule auf, darauf haben wir leider keinen Einfluss.
