### ISSUE TITLE
Zum Hochladen eines Profilphotos muss das Passwort angageben werden

### ISSUE THREAD

**Issue by uho** [McRip/wedeltube#3]
Profilfoto hochladen ohne gleichzeitig das Passwort anzugeben im Dialog "Profil bearbeiten" nicht möglich.

**Comment by LeBar** [comment]
Das ist allerdings genau so auch gedacht. Sobald Änderungen am Profil vorgenommen werden können, muss in jedem Fall das Passwort eingegeben werden, um Missbrauch zu unterbinden.

Sollten keine Fragen mehr auftauchen, schließe ich das Problem im Laufe des Nachmittags.

**Comment by maltehuebner** [comment]
Ich werde heute Abend eine Version veröffentlichen, in der das Feld für das aktuelle Kennwort separat mit einer entsprechenden Erklärung aufgeführt wird.
